// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PleaseWorkDamnIt.Data;

namespace PleaseWorkDamnIt.Migrations
{
    [DbContext(typeof(PleaseWorkDamnItDB))]
    [Migration("20200709011501_AddDeviceScoreColumn")]
    partial class AddDeviceScoreColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PleaseWorkDamnIt.Models.Device", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Area")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Detection")
                        .HasColumnType("int");

                    b.Property<int>("DeviceScore")
                        .HasColumnType("int");

                    b.Property<int>("DownTime")
                        .HasColumnType("int");

                    b.Property<int?>("Function")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfFailures")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWorkingDays")
                        .HasColumnType("int");

                    b.Property<float>("OperationCost")
                        .HasColumnType("real");

                    b.Property<decimal>("PurchasingCost")
                        .HasColumnType("decimal (18,2)");

                    b.Property<DateTime>("PurchasingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Safety")
                        .HasColumnType("int");

                    b.Property<float>("ServiceCost")
                        .HasColumnType("real");

                    b.Property<string>("TypeOfService")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
